/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TrajectoryRouteImport } from './routes/trajectory'
import { Route as BuildsIndexRouteImport } from './routes/builds/index'
import { Route as BuildsSlugRouteImport } from './routes/builds/$slug'
import { Route as ThinkingIndexRouteImport } from './routes/thinking/index'
import { Route as ThinkingSlugRouteImport } from './routes/thinking/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajectoryRoute = TrajectoryRouteImport.update({
  id: '/trajectory',
  path: '/trajectory',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsSlugRoute = BuildsSlugRouteImport.update({
  id: '/builds/$slug',
  path: '/builds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingIndexRoute = ThinkingIndexRouteImport.update({
  id: '/thinking/',
  path: '/thinking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingSlugRoute = ThinkingSlugRouteImport.update({
  id: '/thinking/$slug',
  path: '/thinking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/trajectory': typeof TrajectoryRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
  '/builds/': typeof BuildsIndexRoute
  '/thinking/': typeof ThinkingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/trajectory': typeof TrajectoryRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
  '/builds': typeof BuildsIndexRoute
  '/thinking': typeof ThinkingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/trajectory': typeof TrajectoryRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/thinking/$slug': typeof ThinkingSlugRoute
  '/builds/': typeof BuildsIndexRoute
  '/thinking/': typeof ThinkingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/trajectory'
    | '/builds/$slug'
    | '/thinking/$slug'
    | '/builds/'
    | '/thinking/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/trajectory'
    | '/builds/$slug'
    | '/thinking/$slug'
    | '/builds'
    | '/thinking'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/trajectory'
    | '/builds/$slug'
    | '/thinking/$slug'
    | '/builds/'
    | '/thinking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  TrajectoryRoute: typeof TrajectoryRoute
  BuildsSlugRoute: typeof BuildsSlugRoute
  ThinkingSlugRoute: typeof ThinkingSlugRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
  ThinkingIndexRoute: typeof ThinkingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajectory': {
      id: '/trajectory'
      path: '/trajectory'
      fullPath: '/trajectory'
      preLoaderRoute: typeof TrajectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$slug': {
      id: '/builds/$slug'
      path: '/builds/$slug'
      fullPath: '/builds/$slug'
      preLoaderRoute: typeof BuildsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/': {
      id: '/thinking/'
      path: '/thinking'
      fullPath: '/thinking/'
      preLoaderRoute: typeof ThinkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/$slug': {
      id: '/thinking/$slug'
      path: '/thinking/$slug'
      fullPath: '/thinking/$slug'
      preLoaderRoute: typeof ThinkingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  TrajectoryRoute: TrajectoryRoute,
  BuildsSlugRoute: BuildsSlugRoute,
  ThinkingSlugRoute: ThinkingSlugRoute,
  BuildsIndexRoute: BuildsIndexRoute,
  ThinkingIndexRoute: ThinkingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
